import { MetadataRoute } from 'next'

const moneyPages = [
  '',
  '24-stunden-pflege',
  'kosten',
  'leistungen',
  'ablauf',
  'rechtssicher',
  'qualitaet',
  'kontakt',
  'beratungsgespraech',
  'franchisepartner',
]

const hubs = [
  'ratgeber',
  'pflegegrade',
  'finanzierung',
  'organisation',
  'krankheiten',
  'vergleiche',
  'alltag',
  'rechtliches',
  'regionen',
  'tools',
]

const artikel = [
  'was-ist-24-stunden-pflege',
  '24h-pflege-vs-pflegeheim',
  '24h-pflege-vs-ambulante-pflege',
  'wann-brauche-ich-24h-pflege',
  '24h-pflege-fuer-angehoerige',
  'vorteile-24h-pflege',
  'nachteile-24h-pflege',
  '24h-pflege-checkliste',
  'pflegegrad-1',
  'pflegegrad-2',
  'pflegegrad-3',
  'pflegegrad-4',
  'pflegegrad-5',
  'pflegegrad-beantragen',
  'pflegegrad-widerspruch-einlegen',
  'pflegegrad-erhoehen',
  'pflegegrad-begutachtung-vorbereiten',
  'pflegegrad-aenderung-melden',
  'pflegegrad-ohne-diagnose',
  'pflegegrad-bei-demenz',
  'pflegegrad-nach-schlaganfall',
  'pflegegrad-bei-parkinson',
  'pflegegrade-2025',
  'pflegesachleistungen',
  'verhinderungspflege',
  'kurzzeitpflege',
  'entlastungsbetrag',
  'kombinationsleistung-pflege',
  'pflegehilfsmittel-beantragen',
  'wohnraumanpassung-foerderung',
  'pflege-steuerlich-absetzen',
  'pflegeversicherung-leistungen-uebersicht',
  'sozialhilfe-bei-pflegebedarf',
  'pflegegeld-und-24h-pflege-kombinieren',
  'eigenanteil-24h-pflege-senken',
  'pflegereform-2025',
  'foerderungen-nach-bundesland',
  'pflegekasse-antrag-stellen',
  '24h-pflege-organisieren',
  'pflegekraft-finden',
  'pflegekraft-aus-polen',
  'pflegekraft-aus-bulgarien',
  'pflegekraft-aus-rumaenien',
  'pflegekraft-legal-beschaeftigen',
  'pflegevertrag-aufsetzen',
  'checkliste-pflegekraft-einstellen',
  'pflegekraft-wechseln',
  'pflegekraft-kuendigen',
  'pflege-aus-der-ferne-koordinieren',
  'erste-hilfe-bei-pflegenotfall',
  'notfallplan-pflege',
  'pflegehilfsmittel-organisieren',
  'wohnraumanpassung-planen',
  'hilfsmittel-rollstuhl-beantragen',
  'pflegedokumentation-fuehren',
  'pflegeberater-finden',
  'pflegestuetzpunkte-deutschland',
  'demenz-pflege-zuhause',
  'alzheimer-betreuung-zuhause',
  'schlaganfall-pflege-zuhause',
  'parkinson-pflege-zuhause',
  'multiple-sklerose-pflege',
  'herzinsuffizienz-pflege',
  'diabetes-pflege-senioren',
  'krebspatienten-zuhause-pflegen',
  'pflege-nach-op',
  'osteoporose-pflege-zuhause',
  'copd-pflege-zuhause',
  'sehbehinderung-blindheit-pflege',
  'depression-im-alter-pflege',
  'inkontinenz-pflege-zuhause',
  'wunden-verbinden-zuhause',
  'palliativpflege-zuhause',
  'intensivpflege-zuhause',
  '24h-pflege-vs-pflegeheim-kosten',
  '24h-pflege-anbieter-vergleich',
  'osteuropaeische-pflegekraft-oder-agentur',
  'pflegeheim-kosten-deutschland',
  'selbst-pflegen-oder-24h-pflege',
  'tagespflege-vs-24h-betreuung',
  'kurzzeitpflege-oder-24h-pflege',
  'pflegedienst-oder-24h-kraft',
  'ambulante-vs-stationaere-pflege',
  'pflegende-angehoerige-unterstuetzen',
  'kommunikation-mit-demenzkranken',
  'ernaehrung-pflegebeduerftige-senioren',
  'bewegung-senioren-zuhause',
  'sturzpraevention-senioren',
  'medikamente-senioren-verwalten',
  'schlafprobleme-senioren-loesen',
  'einsamkeit-senioren-bekaempfen',
  'tagesstruktur-demenz',
  'beschaeftigung-senioren-zuhause',
  'barrierefreies-zuhause-gestalten',
  'hausnotruf-senioren',
  'pflege-und-beruf-vereinbaren',
  'pflegezeit-gesetz-angehoerige',
  'burnout-pflegende-angehoerige',
  'pflegeverantwortung-unter-geschwistern',
  'vorsorgevollmacht-erstellen',
  'patientenverfuegung-aufsetzen',
  'betreuungsverfuegung-erstellen',
  'wenn-eltern-pflege-verweigern',
  'pflegevertrag-muster-vorlage',
  'werkvertrag-pflegekraft-muster',
  'scheinselbststaendigkeit-pflege-vermeiden',
  'pflegekraft-sozialversicherung-anmelden',
  'eu-pflegekraft-rechte-pflichten',
  'haftung-pflegehaushalt',
  'datenschutz-pflegesituation',
  'widerspruch-pflegekasse-einlegen',
  'mdk-begutachtung-tipps',
  'pflegemangel-melden-beschwerden',
]

const tools = [
  'pflegegrad-rechner',
  'zuschuss-rechner',
  'eigenanteil-rechner',
  'pflegebedarf-einschaetzen',
  'pflegeheim-kostenvergleich',
  'anbieter-vergleich',
  'checkliste-pflegeuebernahme',
  'pflegevertrag-generator',
  'vollmacht-generator',
]

const regionen = [
  '24h-pflege-nordrhein-westfalen',
  '24h-pflege-bayern',
  '24h-pflege-baden-wuerttemberg',
  '24h-pflege-niedersachsen',
  '24h-pflege-hessen',
  '24h-pflege-rheinland-pfalz',
  '24h-pflege-sachsen',
  '24h-pflege-berlin',
  '24h-pflege-schleswig-holstein',
  '24h-pflege-brandenburg',
  '24h-pflege-sachsen-anhalt',
  '24h-pflege-thueringen',
  '24h-pflege-hamburg',
  '24h-pflege-mecklenburg-vorpommern',
  '24h-pflege-saarland',
  '24h-pflege-bremen',
  '24h-pflege-muenchen',
  '24h-pflege-koeln',
  '24h-pflege-frankfurt',
  '24h-pflege-stuttgart',
  '24h-pflege-duesseldorf',
  '24h-pflege-leipzig',
  '24h-pflege-dortmund',
  '24h-pflege-essen',
  '24h-pflege-dresden',
  '24h-pflege-hannover',
  '24h-pflege-nuernberg',
  '24h-pflege-duisburg',
  '24h-pflege-bochum',
  '24h-pflege-wuppertal',
  '24h-pflege-bielefeld',
  '24h-pflege-bonn',
  '24h-pflege-muenster',
  '24h-pflege-karlsruhe',
  '24h-pflege-mannheim',
  '24h-pflege-augsburg',
  '24h-pflege-wiesbaden',
  '24h-pflege-gelsenkirchen',
  '24h-pflege-moenchengladbach',
  '24h-pflege-braunschweig',
  '24h-pflege-chemnitz',
  '24h-pflege-kiel',
  '24h-pflege-aachen',
  '24h-pflege-halle-saale',
  '24h-pflege-magdeburg',
  '24h-pflege-freiburg',
  '24h-pflege-krefeld',
  '24h-pflege-luebeck',
  '24h-pflege-oberhausen',
  '24h-pflege-erfurt',
  '24h-pflege-mainz',
  '24h-pflege-rostock',
  '24h-pflege-kassel',
  '24h-pflege-hagen',
  '24h-pflege-hamm',
  '24h-pflege-saarbruecken',
  '24h-pflege-muelheim-ruhr',
  '24h-pflege-potsdam',
  '24h-pflege-ludwigshafen',
  '24h-pflege-oldenburg',
  '24h-pflege-leverkusen',
  '24h-pflege-osnabrueck',
  '24h-pflege-solingen',
  '24h-pflege-heidelberg',
  '24h-pflege-herne',
  '24h-pflege-neuss',
  '24h-pflege-darmstadt',
  '24h-pflege-regensburg',
  '24h-pflege-paderborn',
  '24h-pflege-ingolstadt',
  '24h-pflege-wuerzburg',
  '24h-pflege-fuerth',
  '24h-pflege-wolfsburg',
  '24h-pflege-offenbach',
  '24h-pflege-ulm',
  '24h-pflege-heilbronn',
  '24h-pflege-pforzheim',
  '24h-pflege-goettingen',
  '24h-pflege-bottrop',
  '24h-pflege-recklinghausen',
  '24h-pflege-reutlingen',
  '24h-pflege-bremerhaven',
  '24h-pflege-koblenz',
  '24h-pflege-erlangen',
  '24h-pflege-remscheid',
  '24h-pflege-trier',
  '24h-pflege-moers',
  '24h-pflege-salzgitter',
  '24h-pflege-siegen',
  '24h-pflege-hildesheim',
  '24h-pflege-guetersloh',
  '24h-pflege-kaiserslautern',
  '24h-pflege-cottbus',
  '24h-pflege-schwerin',
  '24h-pflege-gera',
  '24h-pflege-iserlohn',
  '24h-pflege-zwickau',
  '24h-pflege-dueren',
  '24h-pflege-dessau',
  '24h-pflege-luedenscheid',
  '24h-pflege-flensburg',
  '24h-pflege-luenen',
  '24h-pflege-jena',
  '24h-pflege-witten',
  '24h-pflege-ratingen',
  '24h-pflege-velbert',
  '24h-pflege-hanau',
  '24h-pflege-marl',
  '24h-pflege-hameln',
  '24h-pflege-bergisch-gladbach',
  '24h-pflege-troisdorf',
  '24h-pflege-viersen',
  '24h-pflege-konstanz',
]

const trust = [
  'ueber-uns',
  'impressum',
  'datenschutz',
  'agb',
  'sitemap',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://primundus.de'
  const now = new Date()

  const toEntry = (
    slug: string,
    priority: number,
    freq: MetadataRoute.Sitemap[0]['changeFrequency']
  ) => ({
    url: slug ? `${base}/${slug}/` : `${base}/`,
    lastModified: now,
    changeFrequency: freq,
    priority,
  })

  return [
    ...moneyPages.map((s) => toEntry(s, s === '' ? 1.0 : 0.95, 'daily')),
    ...hubs.map((s) => toEntry(s, 0.85, 'weekly')),
    ...artikel.map((s) => toEntry(s, 0.75, 'weekly')),
    ...tools.map((s) => toEntry(s, 0.8, 'weekly')),
    ...regionen.map((s) => toEntry(s, 0.7, 'monthly')),
    ...trust.map((s) => toEntry(s, 0.4, 'monthly')),
  ]
}
