// GENERIERT von scripts/build-artikel.mjs — nicht von Hand aendern.
// Quelle ist das BreadcrumbList-Schema der jeweiligen Seite.
export interface Artikel {
  slug: string
  titel: string
  rubrik: string
}

export const ARTIKEL: Artikel[] = [
  { slug: '24-stunden-pflege-kostenuebernahme', titel: "Kostenübernahme 24-Stunden-Pflege", rubrik: 'finanzierung' },
  { slug: '24-stunden-pflege-krankenhausaufenthalt', titel: "Krankenhaus, Ausfall, Wechsel", rubrik: 'organisation' },
  { slug: '24-stunden-pflege-wirkliche-kosten', titel: "Die ehrliche Gesamtrechnung", rubrik: 'finanzierung' },
  { slug: '24h-pflege-checkliste', titel: "24h-Pflege Checkliste", rubrik: 'ratgeber' },
  { slug: '24h-pflege-fuer-angehoerige', titel: "24h-Pflege für Angehörige", rubrik: 'ratgeber' },
  { slug: '24h-pflege-organisieren', titel: "24h-Pflege organisieren", rubrik: 'organisation' },
  { slug: '24h-pflege-vs-ambulante-pflege', titel: "24h-Pflege vs. ambulante Pflege", rubrik: 'vergleiche' },
  { slug: '24h-pflege-vs-pflegeheim', titel: "24h-Pflege vs. Pflegeheim", rubrik: 'ratgeber' },
  { slug: '24h-pflege-vs-pflegeheim-kosten', titel: "24h-Pflege vs. Pflegeheim", rubrik: 'vergleiche' },
  { slug: 'alzheimer-betreuung-zuhause', titel: "Alzheimer Betreuung zuhause", rubrik: 'krankheiten' },
  { slug: 'ambulante-vs-stationaere-pflege', titel: "Ambulante vs. stationäre Pflege", rubrik: 'ratgeber' },
  { slug: 'barrierefreies-zuhause-gestalten', titel: "Barrierefreies Zuhause", rubrik: 'alltag' },
  { slug: 'beratungsgespraech', titel: "Beratungsgespräch", rubrik: 'ratgeber' },
  { slug: 'beschaeftigung-senioren-zuhause', titel: "Beschäftigung Senioren zuhause", rubrik: 'alltag' },
  { slug: 'betreuungsverfuegung-erstellen', titel: "Betreuungsverfügung erstellen", rubrik: 'rechtliches' },
  { slug: 'bewegung-senioren-zuhause', titel: "Bewegung Senioren zuhause", rubrik: 'alltag' },
  { slug: 'burnout-pflegende-angehoerige', titel: "Burnout pflegende Angehörige", rubrik: 'alltag' },
  { slug: 'checkliste-pflegekraft-einstellen', titel: "Checkliste Pflegekraft einstellen", rubrik: 'organisation' },
  { slug: 'copd-pflege-zuhause', titel: "COPD Pflege zuhause", rubrik: 'krankheiten' },
  { slug: 'datenschutz-pflegesituation', titel: "Datenschutz Pflege", rubrik: 'rechtliches' },
  { slug: 'demenz-pflege-zuhause', titel: "Demenz Pflege zuhause", rubrik: 'krankheiten' },
  { slug: 'depression-im-alter-pflege', titel: "Depression im Alter", rubrik: 'krankheiten' },
  { slug: 'diabetes-pflege-senioren', titel: "Diabetes Pflege Senioren", rubrik: 'krankheiten' },
  { slug: 'eigenanteil-24h-pflege-senken', titel: "Eigenanteil senken", rubrik: 'finanzierung' },
  { slug: 'einsamkeit-senioren-bekaempfen', titel: "Einsamkeit bei Senioren", rubrik: 'alltag' },
  { slug: 'entlastungsbetrag', titel: "Entlastungsbetrag", rubrik: 'finanzierung' },
  { slug: 'ernaehrung-pflegebeduerftige-senioren', titel: "Ernährung pflegebedürftiger Senioren", rubrik: 'alltag' },
  { slug: 'erste-hilfe-bei-pflegenotfall', titel: "Erste Hilfe Pflegenotfall", rubrik: 'alltag' },
  { slug: 'eu-pflegekraft-rechte-pflichten', titel: "EU-Pflegekraft Rechte & Pflichten", rubrik: 'rechtliches' },
  { slug: 'foerderungen-nach-bundesland', titel: "Förderungen nach Bundesland", rubrik: 'finanzierung' },
  { slug: 'haftung-pflegehaushalt', titel: "Haftung im Pflegehaushalt", rubrik: 'rechtliches' },
  { slug: 'hausnotruf-senioren', titel: "Hausnotruf Senioren", rubrik: 'alltag' },
  { slug: 'herzinsuffizienz-pflege', titel: "Herzinsuffizienz Pflege", rubrik: 'krankheiten' },
  { slug: 'hilfsmittel-rollstuhl-beantragen', titel: "Rollator & Rollstuhl beantragen", rubrik: 'ratgeber' },
  { slug: 'inkontinenz-pflege-zuhause', titel: "Inkontinenz Pflege zuhause", rubrik: 'krankheiten' },
  { slug: 'intensivpflege-zuhause', titel: "Intensivpflege zuhause", rubrik: 'krankheiten' },
  { slug: 'kombinationsleistung-pflege', titel: "Kombinationsleistung", rubrik: 'finanzierung' },
  { slug: 'kommunikation-mit-demenzkranken', titel: "Kommunikation mit Demenzkranken", rubrik: 'alltag' },
  { slug: 'krebspatienten-zuhause-pflegen', titel: "Krebspatienten zuhause pflegen", rubrik: 'krankheiten' },
  { slug: 'kurzzeitpflege-oder-24h-pflege', titel: "Kurzzeitpflege oder 24h-Pflege", rubrik: 'ratgeber' },
  { slug: 'mdk-begutachtung-tipps', titel: "MDK-Begutachtung Tipps", rubrik: 'pflegegrade' },
  { slug: 'medikamente-senioren-verwalten', titel: "Medikamente Senioren verwalten", rubrik: 'alltag' },
  { slug: 'multiple-sklerose-pflege', titel: "Multiple Sklerose Pflege", rubrik: 'krankheiten' },
  { slug: 'nachteile-24h-pflege', titel: "Nachteile der 24h-Pflege", rubrik: 'ratgeber' },
  { slug: 'notfallplan-pflege', titel: "Notfallplan Pflege", rubrik: 'alltag' },
  { slug: 'osteoporose-pflege-zuhause', titel: "Osteoporose Pflege", rubrik: 'krankheiten' },
  { slug: 'osteuropaeische-pflegekraft-oder-agentur', titel: "Osteuropäische Pflegekraft oder Agentur", rubrik: 'vergleiche' },
  { slug: 'palliativpflege-zuhause', titel: "Palliativpflege zuhause", rubrik: 'krankheiten' },
  { slug: 'parkinson-pflege-zuhause', titel: "Parkinson Pflege zuhause", rubrik: 'krankheiten' },
  { slug: 'patientenverfuegung-aufsetzen', titel: "Patientenverfügung aufsetzen", rubrik: 'alltag' },
  { slug: 'pflege-aus-der-ferne-koordinieren', titel: "Pflege aus der Ferne koordinieren", rubrik: 'organisation' },
  { slug: 'pflege-nach-op', titel: "Pflege nach OP", rubrik: 'krankheiten' },
  { slug: 'pflege-steuerlich-absetzen', titel: "Pflege steuerlich absetzen", rubrik: 'finanzierung' },
  { slug: 'pflege-und-beruf-vereinbaren', titel: "Pflege und Beruf vereinbaren", rubrik: 'alltag' },
  { slug: 'pflegeberater-finden', titel: "Pflegeberater finden", rubrik: 'ratgeber' },
  { slug: 'pflegedienst-oder-24h-kraft', titel: "Pflegedienst oder 24h-Kraft", rubrik: 'vergleiche' },
  { slug: 'pflegedokumentation-fuehren', titel: "Pflegedokumentation führen", rubrik: 'rechtliches' },
  { slug: 'pflegegeld', titel: "Pflegegeld 2026", rubrik: 'finanzierung' },
  { slug: 'pflegegrad-1', titel: "Pflegegrad 1", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-2', titel: "Pflegegrad 2", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-3', titel: "Pflegegrad 3", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-4', titel: "Pflegegrad 4", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-5', titel: "Pflegegrad 5", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-aenderung-melden', titel: "Pflegegrad-Änderung melden", rubrik: 'ratgeber' },
  { slug: 'pflegegrad-beantragen', titel: "Pflegegrad beantragen", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-begutachtung-vorbereiten', titel: "Begutachtung vorbereiten", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-bei-demenz', titel: "Pflegegrad bei Demenz", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-bei-parkinson', titel: "Pflegegrad bei Parkinson", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-erhoehen', titel: "Pflegegrad erhöhen", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-nach-schlaganfall', titel: "Pflegegrad nach Schlaganfall", rubrik: 'pflegegrade' },
  { slug: 'pflegegrad-ohne-diagnose', titel: "Pflegegrad ohne Diagnose", rubrik: 'ratgeber' },
  { slug: 'pflegegrad-widerspruch-einlegen', titel: "Pflegegrad Widerspruch einlegen", rubrik: 'ratgeber' },
  { slug: 'pflegegrade-2025', titel: "Pflegegrade 2025/2026", rubrik: 'ratgeber' },
  { slug: 'pflegeheim-kosten-deutschland', titel: "Pflegeheim Kosten", rubrik: 'vergleiche' },
  { slug: 'pflegehilfsmittel-beantragen', titel: "Pflegehilfsmittel beantragen", rubrik: 'ratgeber' },
  { slug: 'pflegehilfsmittel-organisieren', titel: "Pflegehilfsmittel organisieren", rubrik: 'ratgeber' },
  { slug: 'pflegekasse-antrag-stellen', titel: "Pflegekasse Antrag stellen", rubrik: 'finanzierung' },
  { slug: 'pflegekraft-aus-bulgarien', titel: "Pflegekraft aus Bulgarien", rubrik: 'organisation' },
  { slug: 'pflegekraft-aus-polen', titel: "Pflegekraft aus Polen", rubrik: 'organisation' },
  { slug: 'pflegekraft-aus-rumaenien', titel: "Pflegekraft aus Rumänien", rubrik: 'organisation' },
  { slug: 'pflegekraft-finden', titel: "Pflegekraft finden", rubrik: 'organisation' },
  { slug: 'pflegekraft-kuendigen', titel: "Pflegekraft kündigen", rubrik: 'organisation' },
  { slug: 'pflegekraft-legal-beschaeftigen', titel: "Pflegekraft legal beschäftigen", rubrik: 'organisation' },
  { slug: 'pflegekraft-sozialversicherung-anmelden', titel: "Pflegekraft Sozialversicherung anmelden", rubrik: 'rechtliches' },
  { slug: 'pflegekraft-wechseln', titel: "Pflegekraft wechseln", rubrik: 'organisation' },
  { slug: 'pflegemangel-melden-beschwerden', titel: "Pflegemangel melden", rubrik: 'rechtliches' },
  { slug: 'pflegende-angehoerige-unterstuetzen', titel: "Pflegende Angehörige unterstützen", rubrik: 'alltag' },
  { slug: 'pflegereform-2025', titel: "Pflegereform 2025", rubrik: 'ratgeber' },
  { slug: 'pflegesachleistungen', titel: "Pflegesachleistungen", rubrik: 'finanzierung' },
  { slug: 'pflegestuetzpunkte-deutschland', titel: "Pflegestützpunkte Deutschland", rubrik: 'ratgeber' },
  { slug: 'pflegeverantwortung-unter-geschwistern', titel: "Pflegeverantwortung unter Geschwistern", rubrik: 'alltag' },
  { slug: 'pflegevertrag-aufsetzen', titel: "Pflegevertrag aufsetzen", rubrik: 'organisation' },
  { slug: 'pflegevertrag-muster-vorlage', titel: "Pflegevertrag Muster", rubrik: 'rechtliches' },
  { slug: 'pflegezeit-gesetz-angehoerige', titel: "Pflegezeitgesetz", rubrik: 'rechtliches' },
  { slug: 'scheinselbststaendigkeit-pflege-vermeiden', titel: "Scheinselbstständigkeit vermeiden", rubrik: 'rechtliches' },
  { slug: 'schlafprobleme-senioren-loesen', titel: "Schlafprobleme Senioren", rubrik: 'alltag' },
  { slug: 'schlaganfall-pflege-zuhause', titel: "Schlaganfall Pflege zuhause", rubrik: 'krankheiten' },
  { slug: 'sehbehinderung-blindheit-pflege', titel: "Pflege bei Sehbehinderung", rubrik: 'krankheiten' },
  { slug: 'selbst-pflegen-oder-24h-pflege', titel: "Selbst pflegen oder 24h-Pflege", rubrik: 'vergleiche' },
  { slug: 'sozialhilfe-bei-pflegebedarf', titel: "Sozialhilfe bei Pflegebedarf", rubrik: 'finanzierung' },
  { slug: 'sturzpraevention-senioren', titel: "Sturzprävention Senioren", rubrik: 'alltag' },
  { slug: 'tagespflege-vs-24h-betreuung', titel: "Tagespflege vs. 24h", rubrik: 'vergleiche' },
  { slug: 'tagesstruktur-demenz', titel: "Tagesstruktur bei Demenz", rubrik: 'alltag' },
  { slug: 'verhinderungspflege', titel: "Verhinderungspflege", rubrik: 'finanzierung' },
  { slug: 'vorsorgevollmacht-erstellen', titel: "Vorsorgevollmacht erstellen", rubrik: 'alltag' },
  { slug: 'vorteile-24h-pflege', titel: "Vorteile der 24h-Pflege", rubrik: 'ratgeber' },
  { slug: 'was-ist-24-stunden-pflege', titel: "Was ist 24-Stunden-Pflege?", rubrik: 'ratgeber' },
  { slug: 'wenn-eltern-pflege-verweigern', titel: "Wenn Eltern Pflege verweigern", rubrik: 'alltag' },
  { slug: 'werkvertrag-pflegekraft-muster', titel: "Werkvertrag Pflegekraft", rubrik: 'rechtliches' },
  { slug: 'widerspruch-pflegekasse-einlegen', titel: "Widerspruch einlegen", rubrik: 'pflegegrade' },
  { slug: 'wohnraumanpassung-planen', titel: "Wohnraumanpassung planen", rubrik: 'ratgeber' },
  { slug: 'wunden-verbinden-zuhause', titel: "Wunden verbinden zuhause", rubrik: 'krankheiten' },
]
