// lib/orte-beratung.ts — ERZEUGT, nicht von Hand ändern.
// Erzeugt von seo-reports/baue_orte_beratung.py. Quellen und Begründung stehen dort.
//
// Zweck: Auf jeder Ortsseite soll stehen, WER für die unabhängige Pflegeberatung zuständig
// ist. Das ist die Frage, an der Angehörige als Erstes hängenbleiben, und die Antwort ist
// amtlich belegbar: Ist der Ort kreisfrei, berät die Stadt; sonst der Landkreis.
//
// Was hier bewusst NICHT steht: örtliche Telefonnummern und Adressen der Pflegestützpunkte.
// Bayern und NRW — zusammen die Hälfte unserer Ortsseiten — führen ihre Stützpunkte in einer
// einzigen Tabelle ohne eigene Seite je Kreis. 171 Nummern von Hand zu recherchieren hieße
// 171 Nummern, die dauerhaft stimmen müssen, für Menschen, die in einer Notlage anrufen.
// München und Hamburg haben von Hand geprüfte Blöcke; alle anderen bekommen geprüfte Links.

export interface Beratung {
  /** Amtliche Bezeichnung: „Landkreis Dachau", „Kreis Gütersloh", „Wetteraukreis",
   *  „Region Hannover". Herleitung und Prüfung siehe baue_orte_beratung.py. */
  kreis: string
  /** Kreisfrei? Dann ist die Stadt selbst zuständig, sonst der Landkreis. */
  kreisfrei: boolean
  land: string
}

/** Landesportale der Pflegestützpunkte — alle am 21.09.2026 mit echtem Titel geprüft. */
export const LAENDER: Record<string, { url: string; name: string }> = {
  'Baden-Württemberg': { url: 'https://www.bw-pflegestuetzpunkt.de/', name: 'Pflegestützpunkte Baden-Württemberg' },
  'Bayern': { url: 'https://www.stmgp.bayern.de/pflege/pflege-zu-hause/pflegestuetzpunkte/', name: 'Pflegestützpunkte in Bayern' },
  'Berlin': { url: 'https://www.pflegestuetzpunkteberlin.de/', name: 'Pflegestützpunkte Berlin' },
  'Brandenburg': { url: 'https://www.pflegestuetzpunkte-brandenburg.de/', name: 'Pflegestützpunkte Brandenburg' },
  'Bremen': { url: 'https://www.bremen-pflegestuetzpunkt.de/', name: 'Pflegestützpunkt Bremen' },
  'Hamburg': { url: 'https://www.hamburg.de/pflege/', name: 'Pflege in Hamburg' },
  'Hessen': { url: 'https://www.pflege-in-hessen.de/', name: 'Pflege in Hessen' },
  'Mecklenburg-Vorpommern': { url: 'https://www.pflegestuetzpunkte-mv.de/', name: 'Pflegestützpunkte Mecklenburg-Vorpommern' },
  'Niedersachsen': { url: 'https://www.ms.niedersachsen.de/startseite/themen/pflege/', name: 'Pflege in Niedersachsen' },
  'Nordrhein-Westfalen': { url: 'https://www.mags.nrw/pflegeberatung', name: 'Pflegeberatung und Regionalbüros Alter, Pflege und Demenz NRW' },
  'Rheinland-Pfalz': { url: 'https://www.pflegestuetzpunkte-rlp.de/', name: 'Pflegestützpunkte Rheinland-Pfalz' },
  'Saarland': { url: 'https://www.psp-saar.net/', name: 'Pflegestützpunkte im Saarland' },
  'Sachsen': { url: 'https://www.pflegenetz.sachsen.de/', name: 'PflegeNetz Sachsen' },
  'Sachsen-Anhalt': { url: 'https://www.pflegestuetzpunkte-sachsen-anhalt.de/', name: 'Vernetzte Pflegeberatung Sachsen-Anhalt' },
  'Schleswig-Holstein': { url: 'https://www.schleswig-holstein.de/DE/fachinhalte/P/pflege/beratung/Pflegestuetzpunkte', name: 'Pflegestützpunkte Schleswig-Holstein' },
  'Thüringen': { url: 'https://www.tmasgff.de/soziales/pflege', name: 'Pflege in Thüringen' },
}

/** Schleswig-Holstein ist das einzige Land mit einer eigenen Seite je Kreis. */
export const SH_KREIS_URL = 'https://www.schleswig-holstein.de/DE/fachinhalte/P/pflege/Pflegestuetzpunkte/'

export const ORTE_BERATUNG: Record<string, Beratung> = {
  'aachen': { kreis: 'Städteregion Aachen', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'aalen': { kreis: 'Ostalbkreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'alzey-worms': { kreis: 'Landkreis Alzey-Worms', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'amberg': { kreis: 'Amberg', kreisfrei: true, land: 'Bayern' },
  'aschaffenburg': { kreis: 'Aschaffenburg', kreisfrei: true, land: 'Bayern' },
  'augsburg': { kreis: 'Augsburg', kreisfrei: true, land: 'Bayern' },
  'bad-aibling': { kreis: 'Landkreis Rosenheim', kreisfrei: false, land: 'Bayern' },
  'bad-duerkheim': { kreis: 'Landkreis Bad Dürkheim', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'bad-homburg': { kreis: 'Hochtaunuskreis', kreisfrei: false, land: 'Hessen' },
  'bad-kissingen': { kreis: 'Landkreis Bad Kissingen', kreisfrei: false, land: 'Bayern' },
  'bad-kreuznach': { kreis: 'Landkreis Bad Kreuznach', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'bad-nauheim': { kreis: 'Wetteraukreis', kreisfrei: false, land: 'Hessen' },
  'bad-neuenahr': { kreis: 'Landkreis Ahrweiler', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'bad-reichenhall': { kreis: 'Landkreis Berchtesgadener Land', kreisfrei: false, land: 'Bayern' },
  'bad-toelz': { kreis: 'Landkreis Bad Tölz-Wolfratshausen', kreisfrei: false, land: 'Bayern' },
  'bad-vilbel': { kreis: 'Wetteraukreis', kreisfrei: false, land: 'Hessen' },
  'bamberg': { kreis: 'Bamberg', kreisfrei: true, land: 'Bayern' },
  'bayreuth': { kreis: 'Bayreuth', kreisfrei: true, land: 'Bayern' },
  'bensheim': { kreis: 'Kreis Bergstraße', kreisfrei: false, land: 'Hessen' },
  'berchtesgaden': { kreis: 'Landkreis Berchtesgadener Land', kreisfrei: false, land: 'Bayern' },
  'bergisch-gladbach': { kreis: 'Rheinisch-Bergischer Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'berlin': { kreis: 'Berlin', kreisfrei: true, land: 'Berlin' },
  'bielefeld': { kreis: 'Bielefeld', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'bietigheim-bissingen': { kreis: 'Landkreis Ludwigsburg', kreisfrei: false, land: 'Baden-Württemberg' },
  'bocholt': { kreis: 'Kreis Borken', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'bochum': { kreis: 'Bochum', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'bonn': { kreis: 'Bonn', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'bottrop': { kreis: 'Bottrop', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'braunschweig': { kreis: 'Braunschweig', kreisfrei: true, land: 'Niedersachsen' },
  'bremen': { kreis: 'Bremen', kreisfrei: true, land: 'Bremen' },
  'bremerhaven': { kreis: 'Bremerhaven', kreisfrei: true, land: 'Bremen' },
  'bruchsal': { kreis: 'Landkreis Karlsruhe', kreisfrei: false, land: 'Baden-Württemberg' },
  'charlottenburg': { kreis: 'Berlin', kreisfrei: true, land: 'Berlin' },
  'chemnitz': { kreis: 'Chemnitz', kreisfrei: true, land: 'Sachsen' },
  'cochem': { kreis: 'Landkreis Cochem-Zell', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'cottbus': { kreis: 'Cottbus', kreisfrei: true, land: 'Brandenburg' },
  'dachau': { kreis: 'Landkreis Dachau', kreisfrei: false, land: 'Bayern' },
  'darmstadt': { kreis: 'Darmstadt', kreisfrei: true, land: 'Hessen' },
  'deggendorf': { kreis: 'Landkreis Deggendorf', kreisfrei: false, land: 'Bayern' },
  'dessau': { kreis: 'Dessau-Roßlau', kreisfrei: true, land: 'Sachsen-Anhalt' },
  'dormagen': { kreis: 'Rhein-Kreis Neuss', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'dortmund': { kreis: 'Dortmund', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'dresden': { kreis: 'Dresden', kreisfrei: true, land: 'Sachsen' },
  'dueren': { kreis: 'Kreis Düren', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'duesseldorf': { kreis: 'Düsseldorf', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'duisburg': { kreis: 'Duisburg', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'ebersberg': { kreis: 'Landkreis Ebersberg', kreisfrei: false, land: 'Bayern' },
  'erding': { kreis: 'Landkreis Erding', kreisfrei: false, land: 'Bayern' },
  'erfurt': { kreis: 'Erfurt', kreisfrei: true, land: 'Thüringen' },
  'erlangen': { kreis: 'Erlangen', kreisfrei: true, land: 'Bayern' },
  'eschborn': { kreis: 'Main-Taunus-Kreis', kreisfrei: false, land: 'Hessen' },
  'essen': { kreis: 'Essen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'flensburg': { kreis: 'Flensburg', kreisfrei: true, land: 'Schleswig-Holstein' },
  'frankfurt': { kreis: 'Frankfurt am Main', kreisfrei: true, land: 'Hessen' },
  'freiburg': { kreis: 'Freiburg im Breisgau', kreisfrei: true, land: 'Baden-Württemberg' },
  'freiburg-umland': { kreis: 'Freiburg im Breisgau', kreisfrei: true, land: 'Baden-Württemberg' },
  'freising': { kreis: 'Landkreis Freising', kreisfrei: false, land: 'Bayern' },
  'friedrichshafen': { kreis: 'Bodenseekreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'fuerth': { kreis: 'Fürth', kreisfrei: true, land: 'Bayern' },
  'gaertringen': { kreis: 'Landkreis Böblingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'garmisch-partenkirchen': { kreis: 'Landkreis Garmisch-Partenkirchen', kreisfrei: false, land: 'Bayern' },
  'gauting': { kreis: 'Landkreis Starnberg', kreisfrei: false, land: 'Bayern' },
  'gelsenkirchen': { kreis: 'Gelsenkirchen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'gera': { kreis: 'Gera', kreisfrei: true, land: 'Thüringen' },
  'germering': { kreis: 'Landkreis Fürstenfeldbruck', kreisfrei: false, land: 'Bayern' },
  'germersheim': { kreis: 'Landkreis Germersheim', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'giessen': { kreis: 'Landkreis Gießen', kreisfrei: false, land: 'Hessen' },
  'gilching': { kreis: 'Landkreis Starnberg', kreisfrei: false, land: 'Bayern' },
  'goeppingen': { kreis: 'Landkreis Göppingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'goettingen': { kreis: 'Landkreis Göttingen', kreisfrei: false, land: 'Niedersachsen' },
  'greifswald': { kreis: 'Landkreis Vorpommern-Greifswald', kreisfrei: false, land: 'Mecklenburg-Vorpommern' },
  'grevenbroich': { kreis: 'Rhein-Kreis Neuss', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'guetersloh': { kreis: 'Kreis Gütersloh', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'hagen': { kreis: 'Hagen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'halle-saale': { kreis: 'Halle (Saale)', kreisfrei: true, land: 'Sachsen-Anhalt' },
  'hamburg': { kreis: 'Hamburg', kreisfrei: true, land: 'Hamburg' },
  'hameln': { kreis: 'Landkreis Hameln-Pyrmont', kreisfrei: false, land: 'Niedersachsen' },
  'hamm': { kreis: 'Hamm', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'hanau': { kreis: 'Main-Kinzig-Kreis', kreisfrei: false, land: 'Hessen' },
  'hannover': { kreis: 'Region Hannover', kreisfrei: false, land: 'Niedersachsen' },
  'heidelberg': { kreis: 'Heidelberg', kreisfrei: true, land: 'Baden-Württemberg' },
  'heilbronn': { kreis: 'Heilbronn', kreisfrei: true, land: 'Baden-Württemberg' },
  'heinsberg': { kreis: 'Kreis Heinsberg', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'herne': { kreis: 'Herne', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'hildesheim': { kreis: 'Landkreis Hildesheim', kreisfrei: false, land: 'Niedersachsen' },
  'hochtaunuskreis': { kreis: 'Hochtaunuskreis', kreisfrei: false, land: 'Hessen' },
  'holzkirchen': { kreis: 'Landkreis Miesbach', kreisfrei: false, land: 'Bayern' },
  'ingolstadt': { kreis: 'Ingolstadt', kreisfrei: true, land: 'Bayern' },
  'iserlohn': { kreis: 'Märkischer Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'jena': { kreis: 'Jena', kreisfrei: true, land: 'Thüringen' },
  'kaiserslautern': { kreis: 'Kaiserslautern', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'karlsruhe': { kreis: 'Karlsruhe', kreisfrei: true, land: 'Baden-Württemberg' },
  'kassel': { kreis: 'Kassel', kreisfrei: true, land: 'Hessen' },
  'kaufbeuren': { kreis: 'Kaufbeuren', kreisfrei: true, land: 'Bayern' },
  'kempten': { kreis: 'Kempten (Allgäu)', kreisfrei: true, land: 'Bayern' },
  'kiel': { kreis: 'Kiel', kreisfrei: true, land: 'Schleswig-Holstein' },
  'koblenz': { kreis: 'Koblenz', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'koeln': { kreis: 'Köln', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'konstanz': { kreis: 'Landkreis Konstanz', kreisfrei: false, land: 'Baden-Württemberg' },
  'krefeld': { kreis: 'Krefeld', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'landau': { kreis: 'Landau in der Pfalz', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'landsberg': { kreis: 'Landkreis Landsberg am Lech', kreisfrei: false, land: 'Bayern' },
  'landshut': { kreis: 'Landshut', kreisfrei: true, land: 'Bayern' },
  'leipzig': { kreis: 'Leipzig', kreisfrei: true, land: 'Sachsen' },
  'leverkusen': { kreis: 'Leverkusen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'ludwigsburg': { kreis: 'Landkreis Ludwigsburg', kreisfrei: false, land: 'Baden-Württemberg' },
  'ludwigshafen': { kreis: 'Ludwigshafen am Rhein', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'luebeck': { kreis: 'Lübeck', kreisfrei: true, land: 'Schleswig-Holstein' },
  'luedenscheid': { kreis: 'Märkischer Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'luenen': { kreis: 'Kreis Unna', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'magdeburg': { kreis: 'Magdeburg', kreisfrei: true, land: 'Sachsen-Anhalt' },
  'mainz': { kreis: 'Mainz', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'mannheim': { kreis: 'Mannheim', kreisfrei: true, land: 'Baden-Württemberg' },
  'marburg': { kreis: 'Landkreis Marburg-Biedenkopf', kreisfrei: false, land: 'Hessen' },
  'marl': { kreis: 'Kreis Recklinghausen', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'memmingen': { kreis: 'Memmingen', kreisfrei: true, land: 'Bayern' },
  'miesbach': { kreis: 'Landkreis Miesbach', kreisfrei: false, land: 'Bayern' },
  'minden': { kreis: 'Kreis Minden-Lübbecke', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'moenchengladbach': { kreis: 'Mönchengladbach', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'moenchengladbach-rheydt': { kreis: 'Mönchengladbach', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'moers': { kreis: 'Kreis Wesel', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'muehldorf': { kreis: 'Landkreis Mühldorf a.Inn', kreisfrei: false, land: 'Bayern' },
  'muelheim-ruhr': { kreis: 'Mülheim an der Ruhr', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'muenchen': { kreis: 'München', kreisfrei: true, land: 'Bayern' },
  'muenster': { kreis: 'Münster', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'neubrandenburg': { kreis: 'Landkreis Mecklenburgische Seenplatte', kreisfrei: false, land: 'Mecklenburg-Vorpommern' },
  'neuburg': { kreis: 'Landkreis Neuburg-Schrobenhausen', kreisfrei: false, land: 'Bayern' },
  'neumarkt': { kreis: 'Landkreis Neumarkt i.d.OPf.', kreisfrei: false, land: 'Bayern' },
  'neuss': { kreis: 'Rhein-Kreis Neuss', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'neustadt-weinstrasse': { kreis: 'Neustadt an der Weinstraße', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'nuernberg': { kreis: 'Nürnberg', kreisfrei: true, land: 'Bayern' },
  'nuertingen': { kreis: 'Landkreis Esslingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'oberhausen': { kreis: 'Oberhausen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'offenbach': { kreis: 'Offenbach am Main', kreisfrei: true, land: 'Hessen' },
  'offenburg': { kreis: 'Ortenaukreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'oldenburg': { kreis: 'Oldenburg (Oldenburg)', kreisfrei: true, land: 'Niedersachsen' },
  'osnabrueck': { kreis: 'Osnabrück', kreisfrei: true, land: 'Niedersachsen' },
  'paderborn': { kreis: 'Kreis Paderborn', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'passau': { kreis: 'Passau', kreisfrei: true, land: 'Bayern' },
  'pfaffenhofen': { kreis: 'Landkreis Pfaffenhofen a.d.Ilm', kreisfrei: false, land: 'Bayern' },
  'pforzheim': { kreis: 'Pforzheim', kreisfrei: true, land: 'Baden-Württemberg' },
  'pirmasens': { kreis: 'Pirmasens', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'potsdam': { kreis: 'Potsdam', kreisfrei: true, land: 'Brandenburg' },
  'prien': { kreis: 'Landkreis Rosenheim', kreisfrei: false, land: 'Bayern' },
  'ratingen': { kreis: 'Kreis Mettmann', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'ravensburg': { kreis: 'Landkreis Ravensburg', kreisfrei: false, land: 'Baden-Württemberg' },
  'recklinghausen': { kreis: 'Kreis Recklinghausen', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'regensburg': { kreis: 'Regensburg', kreisfrei: true, land: 'Bayern' },
  'remscheid': { kreis: 'Remscheid', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'reutlingen': { kreis: 'Landkreis Reutlingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'rhein-pfalz-kreis': { kreis: 'Rhein-Pfalz-Kreis', kreisfrei: false, land: 'Rheinland-Pfalz' },
  'rheinisch-bergischer-kreis': { kreis: 'Rheinisch-Bergischer Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'rosenheim': { kreis: 'Rosenheim', kreisfrei: true, land: 'Bayern' },
  'rostock': { kreis: 'Rostock', kreisfrei: true, land: 'Mecklenburg-Vorpommern' },
  'ruesselsheim': { kreis: 'Kreis Groß-Gerau', kreisfrei: false, land: 'Hessen' },
  'saarbruecken': { kreis: 'Regionalverband Saarbrücken', kreisfrei: false, land: 'Saarland' },
  'salzgitter': { kreis: 'Salzgitter', kreisfrei: true, land: 'Niedersachsen' },
  'schweinfurt': { kreis: 'Schweinfurt', kreisfrei: true, land: 'Bayern' },
  'schwerin': { kreis: 'Schwerin', kreisfrei: true, land: 'Mecklenburg-Vorpommern' },
  'siegen': { kreis: 'Kreis Siegen-Wittgenstein', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'sindelfingen': { kreis: 'Landkreis Böblingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'singen': { kreis: 'Landkreis Konstanz', kreisfrei: false, land: 'Baden-Württemberg' },
  'solingen': { kreis: 'Solingen', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'speyer': { kreis: 'Speyer', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'starnberg': { kreis: 'Landkreis Starnberg', kreisfrei: false, land: 'Bayern' },
  'stralsund': { kreis: 'Landkreis Vorpommern-Rügen', kreisfrei: false, land: 'Mecklenburg-Vorpommern' },
  'straubing': { kreis: 'Straubing', kreisfrei: true, land: 'Bayern' },
  'stuttgart': { kreis: 'Stuttgart', kreisfrei: true, land: 'Baden-Württemberg' },
  'traunstein': { kreis: 'Landkreis Traunstein', kreisfrei: false, land: 'Bayern' },
  'trier': { kreis: 'Trier', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'troisdorf': { kreis: 'Rhein-Sieg-Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'tuebingen': { kreis: 'Landkreis Tübingen', kreisfrei: false, land: 'Baden-Württemberg' },
  'ulm': { kreis: 'Ulm', kreisfrei: true, land: 'Baden-Württemberg' },
  'unterschleissheim': { kreis: 'Landkreis München', kreisfrei: false, land: 'Bayern' },
  'vaterstetten': { kreis: 'Landkreis Ebersberg', kreisfrei: false, land: 'Bayern' },
  'velbert': { kreis: 'Kreis Mettmann', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'viersen': { kreis: 'Kreis Viersen', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'villingen-schwenningen': { kreis: 'Schwarzwald-Baar-Kreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'waiblingen': { kreis: 'Rems-Murr-Kreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'waldshut-tiengen': { kreis: 'Landkreis Waldshut', kreisfrei: false, land: 'Baden-Württemberg' },
  'weiden': { kreis: 'Weiden i.d.OPf.', kreisfrei: true, land: 'Bayern' },
  'weilheim': { kreis: 'Landkreis Weilheim-Schongau', kreisfrei: false, land: 'Bayern' },
  'weilheim-schongau': { kreis: 'Landkreis Weilheim-Schongau', kreisfrei: false, land: 'Bayern' },
  'weinheim': { kreis: 'Rhein-Neckar-Kreis', kreisfrei: false, land: 'Baden-Württemberg' },
  'wiesbaden': { kreis: 'Wiesbaden', kreisfrei: true, land: 'Hessen' },
  'wiesbaden-umland': { kreis: 'Wiesbaden', kreisfrei: true, land: 'Hessen' },
  'witten': { kreis: 'Ennepe-Ruhr-Kreis', kreisfrei: false, land: 'Nordrhein-Westfalen' },
  'wittmund': { kreis: 'Landkreis Wittmund', kreisfrei: false, land: 'Niedersachsen' },
  'wolfratshausen': { kreis: 'Landkreis Bad Tölz-Wolfratshausen', kreisfrei: false, land: 'Bayern' },
  'wolfsburg': { kreis: 'Wolfsburg', kreisfrei: true, land: 'Niedersachsen' },
  'worms': { kreis: 'Worms', kreisfrei: true, land: 'Rheinland-Pfalz' },
  'wuerzburg': { kreis: 'Würzburg', kreisfrei: true, land: 'Bayern' },
  'wuppertal': { kreis: 'Wuppertal', kreisfrei: true, land: 'Nordrhein-Westfalen' },
  'zwickau': { kreis: 'Landkreis Zwickau', kreisfrei: false, land: 'Sachsen' },
}
