// Zentrales Städte-Register — generiert am 2026-08-14 (SEO: interne
// Verlinkung der 24h-pflege-Seiten). Neue Städteseite anlegen =
// hier ergänzen, dann erscheint sie automatisch im Regionen-Hub,
// auf der Bundesland-Seite und in den Nachbarort-Blöcken.
export interface Stadt {
  slug: string      // URL-Teil nach /24h-pflege-
  name: string      // Anzeigename
  region: string    // Slug der Bundesland-Seite (24h-pflege-<region>)
}

export const REGION_NAMEN: Record<string, string> = {
  'baden-wuerttemberg': 'Baden-Württemberg',
  'bayern': 'Bayern',
  'brandenburg': 'Berlin & Brandenburg',
  'hessen': 'Hessen',
  'mecklenburg-vorpommern': 'Mecklenburg-Vorpommern',
  'niedersachsen': 'Niedersachsen & Bremen',
  'nordrhein-westfalen': 'Nordrhein-Westfalen',
  'rheinland-pfalz': 'Rheinland-Pfalz',
  'saarland': 'Saarland',
  'sachsen': 'Sachsen',
  'sachsen-anhalt': 'Sachsen-Anhalt',
  'schleswig-holstein': 'Schleswig-Holstein & Hamburg',
  'thueringen': 'Thüringen',
}

export const STAEDTE: Stadt[] = [
  { slug: 'aachen', name: 'Aachen', region: 'nordrhein-westfalen' },
  { slug: 'aalen', name: 'Aalen', region: 'baden-wuerttemberg' },
  { slug: 'alzey-worms', name: 'Kreis Alzey-Worms', region: 'rheinland-pfalz' },
  { slug: 'amberg', name: 'Amberg', region: 'bayern' },
  { slug: 'aschaffenburg', name: 'Aschaffenburg', region: 'bayern' },
  { slug: 'augsburg', name: 'Augsburg', region: 'bayern' },
  { slug: 'bad-aibling', name: 'Bad Aibling', region: 'bayern' },
  { slug: 'bad-duerkheim', name: 'Bad Dürkheim', region: 'rheinland-pfalz' },
  { slug: 'bad-homburg', name: 'Bad Homburg', region: 'hessen' },
  { slug: 'bad-kissingen', name: 'Bad Kissingen', region: 'bayern' },
  { slug: 'bad-kreuznach', name: 'Bad Kreuznach', region: 'rheinland-pfalz' },
  { slug: 'bad-nauheim', name: 'Bad Nauheim', region: 'hessen' },
  { slug: 'bad-neuenahr', name: 'Bad Neuenahr', region: 'rheinland-pfalz' },
  { slug: 'bad-reichenhall', name: 'Bad Reichenhall', region: 'bayern' },
  { slug: 'bad-toelz', name: 'Bad Tölz', region: 'bayern' },
  { slug: 'bad-vilbel', name: 'Bad Vilbel', region: 'hessen' },
  { slug: 'bamberg', name: 'Bamberg', region: 'bayern' },
  { slug: 'bayreuth', name: 'Bayreuth', region: 'bayern' },
  { slug: 'bensheim', name: 'Bensheim', region: 'hessen' },
  { slug: 'berchtesgaden', name: 'Berchtesgaden', region: 'bayern' },
  { slug: 'bergisch-gladbach', name: 'Bergisch Gladbach', region: 'nordrhein-westfalen' },
  { slug: 'berlin', name: 'Berlin', region: 'brandenburg' },
  { slug: 'bielefeld', name: 'Bielefeld', region: 'nordrhein-westfalen' },
  { slug: 'bietigheim-bissingen', name: 'Bietigheim-Bissingen', region: 'baden-wuerttemberg' },
  { slug: 'bocholt', name: 'Bocholt', region: 'nordrhein-westfalen' },
  { slug: 'bochum', name: 'Bochum', region: 'nordrhein-westfalen' },
  { slug: 'bonn', name: 'Bonn', region: 'nordrhein-westfalen' },
  { slug: 'bottrop', name: 'Bottrop', region: 'nordrhein-westfalen' },
  { slug: 'braunschweig', name: 'Braunschweig', region: 'niedersachsen' },
  { slug: 'bremen', name: 'Bremen', region: 'niedersachsen' },
  { slug: 'bremerhaven', name: 'Bremerhaven', region: 'niedersachsen' },
  { slug: 'bruchsal', name: 'Bruchsal', region: 'baden-wuerttemberg' },
  { slug: 'charlottenburg', name: 'Berlin-Charlottenburg', region: 'brandenburg' },
  { slug: 'chemnitz', name: 'Chemnitz', region: 'sachsen' },
  { slug: 'cochem', name: 'Cochem an der Mosel', region: 'rheinland-pfalz' },
  { slug: 'cottbus', name: 'Cottbus', region: 'brandenburg' },
  { slug: 'dachau', name: 'Dachau', region: 'bayern' },
  { slug: 'darmstadt', name: 'Darmstadt', region: 'hessen' },
  { slug: 'deggendorf', name: 'Deggendorf', region: 'bayern' },
  { slug: 'dessau', name: 'Dessau-Roßlau', region: 'sachsen-anhalt' },
  { slug: 'dormagen', name: 'Dormagen', region: 'nordrhein-westfalen' },
  { slug: 'dortmund', name: 'Dortmund', region: 'nordrhein-westfalen' },
  { slug: 'dresden', name: 'Dresden', region: 'sachsen' },
  { slug: 'dueren', name: 'Düren', region: 'nordrhein-westfalen' },
  { slug: 'duesseldorf', name: 'Düsseldorf', region: 'nordrhein-westfalen' },
  { slug: 'duisburg', name: 'Duisburg', region: 'nordrhein-westfalen' },
  { slug: 'ebersberg', name: 'Ebersberg', region: 'bayern' },
  { slug: 'erding', name: 'Erding', region: 'bayern' },
  { slug: 'erfurt', name: 'Erfurt', region: 'thueringen' },
  { slug: 'erlangen', name: 'Erlangen', region: 'bayern' },
  { slug: 'eschborn', name: 'Eschborn', region: 'hessen' },
  { slug: 'essen', name: 'Essen', region: 'nordrhein-westfalen' },
  { slug: 'flensburg', name: 'Flensburg', region: 'schleswig-holstein' },
  { slug: 'frankfurt', name: 'Frankfurt', region: 'hessen' },
  { slug: 'freiburg', name: 'Freiburg', region: 'baden-wuerttemberg' },
  { slug: 'freiburg-umland', name: 'Freiburg & Umland', region: 'baden-wuerttemberg' },
  { slug: 'freising', name: 'Freising', region: 'bayern' },
  { slug: 'friedrichshafen', name: 'Friedrichshafen', region: 'baden-wuerttemberg' },
  { slug: 'fuerth', name: 'Fürth', region: 'bayern' },
  { slug: 'gaertringen', name: 'Gärtringen', region: 'baden-wuerttemberg' },
  { slug: 'garmisch-partenkirchen', name: 'Garmisch-Partenkirchen', region: 'bayern' },
  { slug: 'gauting', name: 'Gauting', region: 'bayern' },
  { slug: 'gelsenkirchen', name: 'Gelsenkirchen', region: 'nordrhein-westfalen' },
  { slug: 'gera', name: 'Gera', region: 'thueringen' },
  { slug: 'germering', name: 'Germering', region: 'bayern' },
  { slug: 'germersheim', name: 'Germersheim', region: 'rheinland-pfalz' },
  { slug: 'giessen', name: 'Giessen', region: 'hessen' },
  { slug: 'gilching', name: 'Gilching', region: 'bayern' },
  { slug: 'goeppingen', name: 'Göppingen', region: 'baden-wuerttemberg' },
  { slug: 'goettingen', name: 'Göttingen', region: 'niedersachsen' },
  { slug: 'greifswald', name: 'Greifswald', region: 'mecklenburg-vorpommern' },
  { slug: 'grevenbroich', name: 'Grevenbroich', region: 'nordrhein-westfalen' },
  { slug: 'guetersloh', name: 'Gütersloh', region: 'nordrhein-westfalen' },
  { slug: 'hagen', name: 'Hagen', region: 'nordrhein-westfalen' },
  { slug: 'halle-saale', name: 'Halle (Saale)', region: 'sachsen-anhalt' },
  { slug: 'hamburg', name: 'Hamburg', region: 'schleswig-holstein' },
  { slug: 'hameln', name: 'Hameln', region: 'niedersachsen' },
  { slug: 'hamm', name: 'Hamm', region: 'nordrhein-westfalen' },
  { slug: 'hanau', name: 'Hanau', region: 'hessen' },
  { slug: 'hannover', name: 'Hannover', region: 'niedersachsen' },
  { slug: 'heidelberg', name: 'Heidelberg', region: 'baden-wuerttemberg' },
  { slug: 'heilbronn', name: 'Heilbronn', region: 'baden-wuerttemberg' },
  { slug: 'heinsberg', name: 'Heinsberg', region: 'nordrhein-westfalen' },
  { slug: 'herne', name: 'Herne', region: 'nordrhein-westfalen' },
  { slug: 'hildesheim', name: 'Hildesheim', region: 'niedersachsen' },
  { slug: 'hochtaunuskreis', name: 'Hochtaunuskreis', region: 'hessen' },
  { slug: 'holzkirchen', name: 'Holzkirchen', region: 'bayern' },
  { slug: 'ingolstadt', name: 'Ingolstadt', region: 'bayern' },
  { slug: 'iserlohn', name: 'Iserlohn', region: 'nordrhein-westfalen' },
  { slug: 'jena', name: 'Jena', region: 'thueringen' },
  { slug: 'kaiserslautern', name: 'Kaiserslautern', region: 'rheinland-pfalz' },
  { slug: 'karlsruhe', name: 'Karlsruhe', region: 'baden-wuerttemberg' },
  { slug: 'kassel', name: 'Kassel', region: 'hessen' },
  { slug: 'kaufbeuren', name: 'Kaufbeuren', region: 'bayern' },
  { slug: 'kempten', name: 'Kempten', region: 'bayern' },
  { slug: 'kiel', name: 'Kiel', region: 'schleswig-holstein' },
  { slug: 'koblenz', name: 'Koblenz', region: 'rheinland-pfalz' },
  { slug: 'koeln', name: 'Köln', region: 'nordrhein-westfalen' },
  { slug: 'konstanz', name: 'Konstanz', region: 'baden-wuerttemberg' },
  { slug: 'krefeld', name: 'Krefeld', region: 'nordrhein-westfalen' },
  { slug: 'landau', name: 'Landau', region: 'rheinland-pfalz' },
  { slug: 'landsberg', name: 'Landsberg', region: 'bayern' },
  { slug: 'landshut', name: 'Landshut', region: 'bayern' },
  { slug: 'leipzig', name: 'Leipzig', region: 'sachsen' },
  { slug: 'leverkusen', name: 'Leverkusen', region: 'nordrhein-westfalen' },
  { slug: 'ludwigsburg', name: 'Ludwigsburg', region: 'baden-wuerttemberg' },
  { slug: 'ludwigshafen', name: 'Ludwigshafen', region: 'rheinland-pfalz' },
  { slug: 'luebeck', name: 'Lübeck', region: 'schleswig-holstein' },
  { slug: 'luedenscheid', name: 'Lüdenscheid', region: 'nordrhein-westfalen' },
  { slug: 'luenen', name: 'Lünen', region: 'nordrhein-westfalen' },
  { slug: 'magdeburg', name: 'Magdeburg', region: 'sachsen-anhalt' },
  { slug: 'mainz', name: 'Mainz', region: 'rheinland-pfalz' },
  { slug: 'mannheim', name: 'Mannheim', region: 'baden-wuerttemberg' },
  { slug: 'marburg', name: 'Marburg', region: 'hessen' },
  { slug: 'marl', name: 'Marl', region: 'nordrhein-westfalen' },
  { slug: 'memmingen', name: 'Memmingen', region: 'bayern' },
  { slug: 'miesbach', name: 'Miesbach', region: 'bayern' },
  { slug: 'minden', name: 'Minden', region: 'nordrhein-westfalen' },
  { slug: 'moenchengladbach', name: 'Mönchengladbach', region: 'nordrhein-westfalen' },
  { slug: 'moenchengladbach-rheydt', name: 'Mönchengladbach-Rheydt', region: 'nordrhein-westfalen' },
  { slug: 'moers', name: 'Moers', region: 'nordrhein-westfalen' },
  { slug: 'muehldorf', name: 'Mühldorf am Inn', region: 'bayern' },
  { slug: 'muelheim-ruhr', name: 'Mülheim an der Ruhr', region: 'nordrhein-westfalen' },
  { slug: 'muenchen', name: 'München', region: 'bayern' },
  { slug: 'muenster', name: 'Münster', region: 'nordrhein-westfalen' },
  { slug: 'neubrandenburg', name: 'Neubrandenburg', region: 'mecklenburg-vorpommern' },
  { slug: 'neuburg', name: 'Neuburg an der Donau', region: 'bayern' },
  { slug: 'neumarkt', name: 'Neumarkt i.d.OPf.', region: 'bayern' },
  { slug: 'neuss', name: 'Neuss', region: 'nordrhein-westfalen' },
  { slug: 'neustadt-weinstrasse', name: 'Neustadt an der Weinstraße', region: 'rheinland-pfalz' },
  { slug: 'nuernberg', name: 'Nürnberg', region: 'bayern' },
  { slug: 'nuertingen', name: 'Nürtingen', region: 'baden-wuerttemberg' },
  { slug: 'oberhausen', name: 'Oberhausen', region: 'nordrhein-westfalen' },
  { slug: 'offenbach', name: 'Offenbach', region: 'hessen' },
  { slug: 'offenburg', name: 'Offenburg', region: 'baden-wuerttemberg' },
  { slug: 'oldenburg', name: 'Oldenburg', region: 'niedersachsen' },
  { slug: 'osnabrueck', name: 'Osnabrück', region: 'niedersachsen' },
  { slug: 'paderborn', name: 'Paderborn', region: 'nordrhein-westfalen' },
  { slug: 'passau', name: 'Passau', region: 'bayern' },
  { slug: 'pfaffenhofen', name: 'Pfaffenhofen', region: 'bayern' },
  { slug: 'pforzheim', name: 'Pforzheim', region: 'baden-wuerttemberg' },
  { slug: 'pirmasens', name: 'Pirmasens', region: 'rheinland-pfalz' },
  { slug: 'potsdam', name: 'Potsdam', region: 'brandenburg' },
  { slug: 'prien', name: 'Prien am Chiemsee', region: 'bayern' },
  { slug: 'ratingen', name: 'Ratingen', region: 'nordrhein-westfalen' },
  { slug: 'ravensburg', name: 'Ravensburg', region: 'baden-wuerttemberg' },
  { slug: 'recklinghausen', name: 'Recklinghausen', region: 'nordrhein-westfalen' },
  { slug: 'regensburg', name: 'Regensburg', region: 'bayern' },
  { slug: 'remscheid', name: 'Remscheid', region: 'nordrhein-westfalen' },
  { slug: 'reutlingen', name: 'Reutlingen', region: 'baden-wuerttemberg' },
  { slug: 'rhein-pfalz-kreis', name: 'Rhein-Pfalz-Kreis', region: 'rheinland-pfalz' },
  { slug: 'rheinisch-bergischer-kreis', name: 'Rheinisch-Bergischer Kreis', region: 'nordrhein-westfalen' },
  { slug: 'rosenheim', name: 'Rosenheim', region: 'bayern' },
  { slug: 'rostock', name: 'Rostock', region: 'mecklenburg-vorpommern' },
  { slug: 'ruesselsheim', name: 'Rüsselsheim', region: 'hessen' },
  { slug: 'saarbruecken', name: 'Saarbrücken', region: 'saarland' },
  { slug: 'salzgitter', name: 'Salzgitter', region: 'niedersachsen' },
  { slug: 'schweinfurt', name: 'Schweinfurt', region: 'bayern' },
  { slug: 'schwerin', name: 'Schwerin', region: 'mecklenburg-vorpommern' },
  { slug: 'siegen', name: 'Siegen', region: 'nordrhein-westfalen' },
  { slug: 'sindelfingen', name: 'Sindelfingen', region: 'baden-wuerttemberg' },
  { slug: 'singen', name: 'Singen', region: 'baden-wuerttemberg' },
  { slug: 'solingen', name: 'Solingen', region: 'nordrhein-westfalen' },
  { slug: 'speyer', name: 'Speyer', region: 'rheinland-pfalz' },
  { slug: 'starnberg', name: 'Starnberg', region: 'bayern' },
  { slug: 'stralsund', name: 'Stralsund', region: 'mecklenburg-vorpommern' },
  { slug: 'straubing', name: 'Straubing', region: 'bayern' },
  { slug: 'stuttgart', name: 'Stuttgart', region: 'baden-wuerttemberg' },
  { slug: 'traunstein', name: 'Traunstein', region: 'bayern' },
  { slug: 'trier', name: 'Trier', region: 'rheinland-pfalz' },
  { slug: 'troisdorf', name: 'Troisdorf', region: 'nordrhein-westfalen' },
  { slug: 'tuebingen', name: 'Tübingen', region: 'baden-wuerttemberg' },
  { slug: 'ulm', name: 'Ulm', region: 'baden-wuerttemberg' },
  { slug: 'unterschleissheim', name: 'Unterschleissheim', region: 'bayern' },
  { slug: 'vaterstetten', name: 'Vaterstetten', region: 'bayern' },
  { slug: 'velbert', name: 'Velbert', region: 'nordrhein-westfalen' },
  { slug: 'viersen', name: 'Viersen', region: 'nordrhein-westfalen' },
  { slug: 'villingen-schwenningen', name: 'Villingen-Schwenningen', region: 'baden-wuerttemberg' },
  { slug: 'waiblingen', name: 'Waiblingen', region: 'baden-wuerttemberg' },
  { slug: 'waldshut-tiengen', name: 'Waldshut-Tiengen', region: 'baden-wuerttemberg' },
  { slug: 'weiden', name: 'Weiden i.d. Oberpfalz', region: 'bayern' },
  { slug: 'weilheim', name: 'Weilheim', region: 'bayern' },
  { slug: 'weilheim-schongau', name: 'Weilheim-Schongau', region: 'bayern' },
  { slug: 'weinheim', name: 'Weinheim', region: 'baden-wuerttemberg' },
  { slug: 'wiesbaden', name: 'Wiesbaden', region: 'hessen' },
  { slug: 'wiesbaden-umland', name: 'Wiesbaden & Umland', region: 'hessen' },
  { slug: 'witten', name: 'Witten', region: 'nordrhein-westfalen' },
  { slug: 'wittmund', name: 'Wittmund', region: 'niedersachsen' },
  { slug: 'wolfratshausen', name: 'Wolfratshausen', region: 'bayern' },
  { slug: 'wolfsburg', name: 'Wolfsburg', region: 'niedersachsen' },
  { slug: 'worms', name: 'Worms', region: 'rheinland-pfalz' },
  { slug: 'wuerzburg', name: 'Würzburg', region: 'bayern' },
  { slug: 'wuppertal', name: 'Wuppertal', region: 'nordrhein-westfalen' },
  { slug: 'zwickau', name: 'Zwickau', region: 'sachsen' },
]

